// import type { Metadata } from "next";
import "./globals.css";
import { Geist } from "next/font/google";
import { cn } from "@/lib/utils";
import { Toaster } from "@/components/ui/sonner";
import Navbar from "@/components/shared/Navbar";
import { getMe } from "@/service/getMe";
// import { Navbar } from "@/components/shared/Navbar";

const geist = Geist({ subsets: ['latin'], variable: '--font-sans' });


// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default async function RootLayout({ children }: LayoutProps<"/">) {
  const user = await getMe();
  return (
    <html
      lang="en"
      className={cn("h-full antialiased", "font-sans", geist.variable)}>
      <body className="">
        <Navbar user={user} />
        <main className="min-w-7xl mx-auto pt-20">
          {children}
        </main>

        <Toaster position="top-center" />

      </body>
    </html>
  );
}
